version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: motion
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/motion
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    ports:
      - "8000:8000"

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   volumes:
  #     - ./frontend:/app
  #   environment:
  #     VITE_API_URL: http://localhost:8000
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend

volumes:
  db_data:
